name: infinitywords
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0
  multiple_result: ^4.0.0
  get_it: ^7.4.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dart_openai: ^1.9.91
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  envied_generator: ^0.3.0+3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/app/
    - lib/shared/assets/icons/
    - lib/shared/assets/images/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: lib/shared/assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700
          style: normal
        - asset: lib/shared/assets/fonts/IBMPlexMono-Light.ttf
          weight: 300
          style: normal
        - asset: lib/shared/assets/fonts/IBMPlexMono-Medium.ttf
          weight: 500
          style: normal
        - asset: lib/shared/assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
          style: normal
        - asset: lib/shared/assets/fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
          style: normal
